# version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yii2_app
    working_dir: /var/www/html
    ports:
      - "80:80"
      - "9003:9003"
    volumes:
      - ./www_app:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: yii2_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: yii2_db
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
