services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yii2_app
    working_dir: /var/www
    ports:
      - "80:80"
      - "3000:3000"
#      - "9003:9003"
    volumes:
      - ./www_app:/var/www
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    container_name: yii2_frontend
    working_dir: /app
    volumes:
      - ./www_front:/app
      - ./www_app/web/public/html:/app/dist
    command: ["sh", "-c", "npm install && npm run build"]

  db:
    image: mysql:8.0
    container_name: yii2_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: yii2_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
