<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/** @var yii\web\View $this */
/** @var app\gii\routeViewer\RouteViewerGenerator $generator */

$form = ActiveForm::begin();
echo $form->field($generator, 'appContext')->dropDownList([
    'web' => 'Web',
    'api' => 'API',
]);
echo Html::submitButton('Refresh', ['class' => 'btn btn-primary']);
ActiveForm::end();

echo Html::tag('h3', 'Registered Routes', ['style' => 'margin-top:20px;']);

$rules = $generator->getRoutes();

echo "<table class='table table-bordered table-striped'>";
echo "<thead><tr><th>#</th><th>Pattern</th><th>Route</th><th>Class</th></tr></thead><tbody>";

foreach ($rules as $i => $rule) {
    echo "<tr>";
    echo "<td>" . ($i + 1) . "</td>";
    echo "<td>" . Html::encode($rule->name ?: (method_exists($rule, '__toString') ? $rule->__toString() : '-')) . "</td>";
    echo "<td>" . Html::encode($rule->route ?? '-') . "</td>";
    echo "<td>" . Html::encode(get_class($rule)) . "</td>";
    echo "</tr>";
}

echo "</tbody></table>";
echo Html::tag('p', 'Total routes: ' . count($rules), ['style' => 'margin-top:20px;']);
echo Html::tag('p', 'Generated by Yii2 Gii Route Viewer', ['style' => 'margin-top:20px;']);
