<?php
use yii\helpers\Html;

/** @var array $routes */
?>

<h3>Registered Routes</h3>

<div class="table-responsive">
    <table class="table table-bordered table-striped table-hover">
        <thead>
        <tr>
            <th>#</th>
            <th>Method</th>
            <th>Pattern</th>
            <th>Route</th>
            <th>Class</th>
            <th>Status</th>
        </tr>
        </thead>
        <tbody>
        <?php $i = 1; foreach ($routes as $route): ?>
            <?php
            $rowClass = '';
            if ($route['valid'] === false) {
                $rowClass = 'table-danger';
            } elseif ($route['valid'] === null) {
                $rowClass = 'table-warning';
            }
            ?>
            <tr class="<?= $rowClass ?>">
                <td style="white-space: nowrap"><?= $i++ ?></td>
                <td><?= Html::encode($route['methods']) ?></td>
                <td style="white-space: nowrap"><?= Html::encode($route['pattern']) ?></td>
                <td style="white-space: nowrap"><?= Html::encode($route['route']) ?></td>
                <td style="white-space: nowrap"><?= Html::encode($route['class']) ?></td>
                <td title="<?= Html::encode($route['status_hint']) ?>">
                    <?= Html::encode($route['status_short']) ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<p>Total routes: <?= count($routes) ?></p>
<p>Generated by Yii2 Gii Route Viewer</p>
